### ISSUE TITLE
Does not work in django v1.8.0

### ISSUE THREAD

**Issue by ghost** [willhardy/django-seo#51]
I got this error bellow:

```
Traceback (most recent call last):
  File "base/seo.py", line 3, in <module>
    from rollyourown import seo
  File "/home/foo/.virtualenvs/retie/local/lib/python2.7/site-packages/rollyourown/seo/__init__.py", line 4, in <module>
    from rollyourown.seo.base import Metadata, Tag, KeywordTag, MetaTag, Raw, Literal, get_metadata, get_linked_metadata
  File "/home/foo/.virtualenvs/retie/local/lib/python2.7/site-packages/rollyourown/seo/base.py", line 17, in <module>
    from django.utils.hashcompat import md5_constructor
ImportError: No module named hashcompat
```

**Comment by ffeast** [comment]
Same for Django 1.7:

```
$ pip freeze | grep -i django
Django==1.7.4
```

```
  File "/home/oleg/.virtualenvs/prj/local/lib/python2.7/site-packages/rollyourown/seo/__init__.py", line 4, in <module>
    from rollyourown.seo.base import Metadata, Tag, KeywordTag, MetaTag, Raw, Literal, get_metadata, get_linked_metadata
  File "/home/oleg/.virtualenvs/prj/local/lib/python2.7/site-packages/rollyourown/seo/base.py", line 17, in <module>
    from django.utils.hashcompat import md5_constructor
ImportError: No module named hashcompat
```

**Comment by felixcheruiyot** [comment]
Has anyone manage to have a look at this?

**Comment by romansalin** [comment]
Module hashcompat was removed in Django 1.6. Check this out https://github.com/romansalin/django-seo2

**Comment by sabinem** [comment]
To romansalin, what excactly does you comment mean in this. Should I just take your repo instead of this? Can it be installed with pip? Why is this repo not fixed on this issue of being compatible with Django 1.9? I appreciate an answer to this, since I want to decide what to do with my seo.

**Comment by jcastiarena** [comment]
Anybody got an answer on this issue? Having the same problem with Django 1.8.5

```
pip freeze | grep Django==
Django==1.8.5

python manage.py syncdb
  File "/Users/saverio/workspace/ontdek/oba/lib/python2.7/site-packages/rollyourown/seo/base.py", line 17, in <module>
    from django.utils.hashcompat import md5_constructor
ImportError: No module named hashcompat
```

**Comment by jcastiarena** [comment]
I believe the file in https://pypi.python.org/simple/djangoseo/ is outdated (has the unfixed code). Pip would take it from there. Try `pip install -v -v -v djangoseo` (see http://stackoverflow.com/a/17153977/2158516)

**Comment by romansalin** [comment]
@sabinem, actually it is the fork from this repo, which is no longer maintained. I made there some improves and bugfixes. Currently this package can't be installed with pip, but I'm going to add it to the pypi. The compatibility with Django 1.9 will be added soon too.

**Comment by jcastiarena** [comment]
@romansalin thanks. Any estimation on when will you be able to add it pypi?

**Comment by romansalin** [comment]
@jcastiarena here is the new repo https://github.com/romansalin/django-seo2. I've published this on PyPI, so now you can install django-seo2 via pip: `pip install django-seo2`. Supported Django 1.9 with python 2 and 3.

**Comment by mic159** [comment]
There is a major bug in the django-seo2 package, but @romansalin has stopped responding and wont publish the fix. Its been broken for almost a year now.

Is there any other forks that have better support?

**Comment by snig-b** [comment]
Any other forks that have fixed the hashcompat issue? It's not working in Django 1.6.5 also
